import { build } from "esbuild";
import { copyFile, mkdir } from "node:fs/promises";

// Keep packaged icons in sync with the approved Senseek brand assets.
await mkdir("extension/icons", { recursive: true });
await copyFile("assets/senseek/senseek-icon.svg", "extension/icons/mark.svg");
for (const size of [16, 32, 48, 128]) {
  await copyFile(`assets/senseek/exports/icon-${size}.png`, `extension/icons/icon-${size}.png`);
}

await build({
  entryPoints: ["src/content.js"],
  outfile: "extension/content.js",
  bundle: true,
  format: "iife",
  target: "chrome111",
  loader: { ".css": "text", ".svg": "text" },
  banner: { js: "// Generated by npm run build from src/. Do not edit this file directly." },
});
console.log("Built extension/content.js. The extension is ready to load.");
