import { build } from "esbuild";
import "./sync-icons.mjs";

await build({
  entryPoints: ["src/content.js", "src/unavailable.js"],
  outdir: "extension",
  bundle: true,
  format: "iife",
  target: "chrome127",
  loader: { ".css": "text", ".svg": "text" },
  banner: { js: "// Generated by npm run build from src/. Do not edit this file directly." },
});
console.log("Built the page search and shared notice panel. The extension is ready to load.");
